translations = {
    '"Fuel Volume"': '"燃料箱"',
    '"Brake Force Multiplier"': '"制动力度"',
    '"Front/Rear Bias"': '"前后刹车分配"',
    '"Short Compression"': '"低速压缩行程"',
    '"Mid Compression"': '"中速压缩行程"',
    '"Long Compression"': '"高速压缩行程"',
    '"Short Rebound"': '"避震器低速回弹行程"',
    '"Long Rebound"': '"避震器高速回弹行程"',
    '"Compression damping"': '"压缩阻尼力度"',
    '"Rebound Damping"': '"回弹阻尼"',
    '"Setup-Specific Force Feedback Multiplier"': '"方向盘力反馈"',
    '"Bump Damping"': '"压缩阻尼"',
    '"Fast Bump Damping"': '"高速压缩阻尼"',
    '"Helper Spring Rate"': '"辅助弹簧硬度"',
    '"Fast Rebound Damping"': '"高速回弹阻尼"',
    '"Main Spring Rate"': '"主弹簧硬度"',
    '"Spring Height"': '"弹簧高度"',
    '"Final Drive Gear Ratio"': '"差速器齿比"',
    '"Anti-Roll Spring Rate"': '"防倾杆刚度"',
    '"Toe Left/Right Trim"': '"左右轮束脚"',
    '"Toe Adjust"': '"束脚"',
    '"Wheel Offset"': '"轮毂偏距"',
    '"Tire Ballast"': '"车轮负载"',
    '"Tire Pressure"': '"轮胎气压"',
    '"Minimum Gear"': '"N2o介入挡位"',
    '"Added Power"': '"N2o增压功率"',
    '"Minimum RPM"': '"N2o介入转速"',
    '"Camber Adjust"': '"前倾角"',
    '"Caster Adjust"': '"前束脚"',
    '"Base Torque Split"': '"加速扭矩分配"',
    '"Power Lock Rate"': '"减速扭矩锁定"',
    '"Pre-load Torque"': '"预加载扭矩"',
    '"RPM Limit Cut Time"': '"转速限制时间间隔"',
    '"RPM Limit"': '"转速限制"',
    '"Wastegate Pressure"': '"排气压力阀"',
    '"Spring Rate"': '"弹簧硬度"',
    '"1st Gear Ratio"': '"1档齿轮比"',
    '"2nd Gear Ratio"': '"2档齿轮比"',
    '"3rd Gear Ratio"': '"3档齿轮比"',
    '"4th Gear Ratio"': '"4档齿轮比"',
    '"5th Gear Ratio"': '"5档齿轮比"',
    '"6th Gear Ratio"': '"6档齿轮比"',
    '"Reverse Gear Ratio"': '"倒挡齿轮比"',
    '"Coast Lock Rate"': '"滑行减速齿比"',
    '"Forward Lock Rate"': '"前轴锁定齿比"',
    '"Turbo Boost Pressure"': '"涡轮增压压力"',
    '"Spring Collar Height"': '"弹簧底座高度"',
    '"Frame"': '"车架"',
    '"Brake Line Lock"': '"制动管路锁定"',
    '"Anti-Lock Braking System"': '"防抱死制动系统"',
    '"Rear Driveshaft"': '"后传动轴"',
    '"Left Fire Extinguisher"': '"左侧灭火器"',
    '"Right Fire Extinguisher"': '"右侧灭火器"',
    '"Floor Jack"': '"千斤顶"',
    '"GPS Antenna"': '"GPS天线"',
    '"Light Bar"': '"灯条"',
    '"Muffler"': '"消音器"',
    '"Number Plates"': '"车牌架"',
    '"Oil Bottles"': '"机油瓶"',
    '"Rear Frame"': '"后车架"',
    '""Taillight Bar""': '"尾灯条"',
    '"Tool Box"': '"工具箱"',
    '"Left Window Net"': '"左窗网"',
    '"Right Window Net"': '"右窗网"',
    '"Radiator"': '"散热器"',
    '"Front Bumper"': '"前保险杠"',
    '"Rear Bumper"': '"后保险杠"',
    '"Body"': '"车身"',
    '"Front License Plate"': '"前车牌"',
    '"Rear License plate"': '"后车牌"',
    '"Fuel Cell"': '"燃料电池"',
    '"License Plate Design"': '"车牌风格"',
    '"Paint Design"': '"涂装"',
    '"Glass Tint"': '"玻璃膜"',
    '"Navigation Unit"': '"导航设备"',
    '"Center High Mounted Stop Light"': '"尾部刹车灯"',
    '"Hood"': '"引擎盖"',
    '"Running Boards"': '"侧边脚踏"',
    '"Left Spotlight"': '"左探照灯"',
    '"Right Spotlight"': '"右探照灯"',
    '"Windshield"': '"挡风玻璃"',
    '"Interior Color"': '"内饰颜色"',
    '"Horn"': '"喇叭"',
    '"Front Left Door"': '"左车门"',
    '"Front Right Door"': '"右车门"',
    '"Front Left Door Detent"': '"左门限位器"',
    '"Front Right Door Detent"': '"右门限位器"',
    '"Dashboard"': '"仪表台"',
    '"Interior Accessories"': '"内饰配件"',
    '"Shifter"': '"挡杆"',
    '"Range Selector"': '"挡位选择器"',
    '"Steering Wheel"': '"方向盘"',
    '"Roof Accessory"': '"车顶配件"',
    '"Light Accessory"': '"灯配件"',
    '"Front Seat"': '"前排座椅"',
    '"Driver Seat"': '"驾驶座椅"',
    '"Passenger Seat"': '"副驾驶座椅"',
    '"Front Left Race Seat"': '"驾驶位赛车座椅"',
    '"Front Right Race Seat"': '"副驾驶赛车座椅"',
    '"Seat Color"': '"座椅颜色"',
    '"Front Left Fender"': '"左前翼子板"',
    '"Front Right Fender"': '"右前翼子板"',
    '"Grille Bars"': '"散热器格栅"',
    '"Left Headlight"': '"左侧大灯"',
    '"Right Headlight"': '"右侧大灯"',
    '"Front Left Signal"': '"前左转向灯"',
    '"Front Right Signal"': '"前右转向灯"',
    '"Front Suspension"': '"前悬挂系统"',
    '"Rear Suspension"': '"后悬挂系统"',
    '"Front Bump Stops"': '"前减震行程限位器"',
    '"Rear Bump Stops"': '"车牌架"',
    '"Front Driveshaft"': '"前传动轴"',
    '"Rear Shocks"': '"后减震器"',
    '"Front Shocks"': '"前减震器"',
    '"Rear Springs"': '"后悬挂弹簧"',
    '"Steering"': '"转向拉杆"',
    '"Front Sway Bar"': '"前防倾杆"',
    '"Rear Sway Bar"': '"后防倾杆"',
    '"Front Spindles"': '"前轮羊角"',
    '"Rear Spindles"': '"后轮羊角"',
    '"Front Brakes"': '"前刹车"',
    '"Rear Brakes"': '"后刹车"',
    '"Front Brake Pads"': '"前刹车片"',
    '"Rear Brake Pads"': '"后刹车片"',
    '"Front Differential"': '"差速器"',
    '"Rear Differential"': '"后差速器"',
    '"Front Axle Shafts"': '"前轴"',
    '"Front Final Drive"': '"前差速齿比"',
    '"Rear Final Drive"': '"后差速齿比"',
    '"Front Wheels"': '"前轮毂"',
    '"Rear Wheel"': '"后轮毂"',
    '"Front Tires"': '"前轮胎"',
    '"Rear Tires"': '"后轮胎"',
    '"Engine"': '"引擎"',
    '"Nitrous Oxide System"': '"一氧化二氮系统"',
    '"Engine Management"': '"行车电脑"',
    '"Engine Long Block"': '"引擎缸体"',
    '"Engine Mounts"': '"引擎机爪垫"',
    '"Intake"': '"进气系统"',
    '"Oil Pan"': '"油底壳"',
    '"Exhaust Manifold"': '"排气歧管"',
    '"Exhaust"': '"排气"',
    '"Transmission"': '"变速箱"',
    '"Torque Converter"': '"扭矩放大器"',
    '"Transfer Case"': '"传动分动箱"',
    '"Front Left Beacon Light"': '"前左侧警示灯"',
    '"Front Right Beacon Light"': '"前右侧警示灯"',
    '"Rear Left Beacon Light"': '"后左侧警示灯"',
    '"Rear Right Beacon Light"': '"后右侧警示灯"',
    '"Rear Left Bench"': '"左后座椅"',
    '"Rear Right Bench"': '"右后座椅"',
    '"Engine Cover"': '"引擎隔热罩"',
    '"Load"': '"装载"',
    '"Fuel Tank"': '"燃料箱"',
    '"Rear Cab Gate"': '"驾驶室隔断"',
    '"Left Mirror"': '"左后视镜"',
    '"Right Mirror"': '"右后视镜"',
    '"Front Left Quarter Glass"': '"前左侧小窗"',
    '"Front Right Quarter Glass"': '"前右侧小窗"',
    '"Left Running Board"': '"左侧脚踏板"',
    '"Right Running Board"': '"右侧脚踏板"',
    '"Rear Left Seat"': '"后排左侧座椅"',
    '"Rear Right Seat"': '"后排右侧座椅"',
    '"Front Siren"': '"前报警器"',
    '"Rear Siren"': '"后报警器"',
    '"Snorkel"': '"涉水喉"',
    '"Left Taillight"': '"左侧尾灯"',
    '"Right Taillight"': '"右侧尾灯"',
    '"Tire Pressure Management System"': '"胎压管理系统"',
    '"Rear License Plate"': '"后牌照架"',
    '"Left Auxilary Light"': '"左侧辅灯"',
    '"Right Auxilary Light"': '"右侧辅灯"',
    '"Left Light Cover"': '"左侧灯罩"',
    '"Right Light Cover"': '"右侧辅灯"',
    '"Chassis"': '"底盘"',
    '"Auxilary Fog Lights"': '"辅助雾灯"',
    '"Fog Light Covers"': '"辅助灯灯罩"',
    '"Rear Rear Differential"': '"尾轴差速器"',
    '"Rear Rear Final Drive"': '"尾轴差速器齿比"',
    '"Rev Limiter"': '"转速限制器"',
    '"Flywheel"': '"飞轮"',
    '"Propshaft"': '"传动轴"',
    '"Range Box"': '"分动箱"',
    '"Front Springs"': '"前弹簧"',
    '"Front Wheel Hubs"': '"前轮法兰盘"',
    '"Front Hubcaps"': '"前轮毂盖"',
    '"Rear Limit Straps"': '"后轴限位器"',
    '"Rear Rear Limit Straps"': '"尾轴限位器"',
    '"Rear Leaf Springs"': '"后板簧"',
    '"Rear Wheels"': '"后轮毂"',
    '"Rear Rear Brake Shoes"': '"尾轴刹车片"',
    '"Rear Tow Hitch"': '"后拖车钩"',
    '"Front Left Door Glass"': '"前左侧门玻璃"',
    '"Front Right Door Glass"': '"前右侧门玻璃"',
    '"Left Fuel Can Holder"': '"左侧燃油支架"',
    '"Left Fuel Can"': '"左侧燃油箱"',
    '"Right Fuel Can Holder"': '"右侧燃油支架"',
    '"Right Fuel Can"': '"右侧燃油箱"',
    '"Left Headlight Guard"': '"左侧大灯护罩"',
    '"Right Headlight Guard"': '"右侧大灯护罩"',
    '"Rear Door"': '"后门"',
    '"Rear Door Glass"': '"后门玻璃"',
    '"Spare Wheel"': '"备胎轮毂"',
    '"Spare Tire"': '"备胎"',
    '"Spare Wheel Cover"': '"备胎罩"',
    '"Body Accessory"': '"车身配件"',
    '"Front Rollcage Lights"': '"前辅灯"',
    '"Front Rollcage Roof Lights"': '"车顶辅灯"',
    '"Siren Audio"': '"警报类型"',
    '"Right Rear Door"': '"右后侧门"',
    '"Left Rear Door"': '"左后侧门"',
    '"Right Rear Door Glass"': '"右后侧门玻璃"',
    '"Left Rear Door Glass"': '"左后侧门玻璃"',
    '"Rear Rear Wheels"': '"尾轴轮毂"',
    '"Rear Rear Hubcaps"': '" 尾轴轮毂盖"',
    '"Front Seat Load"': '"副驾驶座椅装载"',
    '"Rear Rear Wheel Hubs"': '"尾轴轮毂法兰盘"',
    '"Rear Rear Shocks"': '"尾轴减震器"',
    '"Range Box Ratios"': '"分动箱齿轮比"', #
    '"Backlight"': '"后玻璃"',
    '"Driving & Safety Electronics"': '"车身稳定系统"',
    '"Lettering"': '"贴纸"',
    '"Roll Cage"': '"防滚架"',
    '"Rear Seats"': '"后排座椅"',
    '"Left Side Skirt"': '"左侧侧裙"',
    '"Right Side Skirt"': '"右侧侧裙"',
    '"Tow Hitch"': '"拖车钩"',
    '"Trim"': '"装饰条"',
    '"Trunk Load"': '"后备箱装载"',
    '"Undertray"': '"底部护板"',
    '"Interior Design"': '"内饰风格"',
    '"Front Splitter"': '"前唇"',
    '"Interior"': '"内饰"', #
    '"Center Console"': '"中控台"',
    '"Dashboard Accessory"': '"内饰配件"',
    '"Gauge"': '"仪表"',
    '"Shift Light"': '"换挡指示灯"',
    '"Front Left Fender Flare"': '"前左侧翼子板宽体"',
    '"Front Right Fender Flare"': '"前右侧翼子板宽体"',
    '"Grille"': '"散热格栅"',
    '"Grille Badge"': '"格栅标"',
    '"Quarter Panels"': '"后翼子板"', #
    '"Rear Left Fender Flare"': '"左后翼子板宽体"',
    '"Rear Right Fender Flare"': '"右后翼子板宽体"',
    '"Front Struts"': '"前支柱"',
    '"Rear Struts"': '"后支柱"',
    '"Power Steering"': '"转向助力系统"',
    '"Rear Subframe Mounts"': '"后元宝梁衬套"',
    '"Rear Halfshafts"': '"后半轴"',
    '"Front Halfshafts"': '"半轴"',
    '"Trunk"': '"后备箱"',
    '"Trunk Lettering"': '"后备箱字标"',
    '"Trunk Accessory"': '"后备箱配件"', #
    '"Rear Left Door"': '"左侧后门"',
    '"Rear Right Door"': '"右侧后门"',
    '"Rear Left Door Detent"': '"左后门限位器"',
    '"Rear Right Door Detent"': '"右后门限位器"',
    '"Rear Left Door Flare"': '"左后门翼子板"',
    '"Rear Right Door Flare"': '"右后门翼子板"',
    '"Rear Left Door Glass"': '"左后门玻璃"',
    '"Rear Right Door Glass"': '"右后门玻璃"',
    '"Rear Left Door Panel"': '"左后门内饰板"',
    '"Rear Right Door Panel"': '"右后门内饰板"',
    '"Exhaust Manifolds"': '"排气歧管"',
    '"Exhaust Mufflers"': '"排气消音器"',
    '"Spoiler"': '"尾翼"',
    '"Speed Limiter"': '"限速器"',
    '"Front Left Door Panel"': '"前门左内饰板"',
    '"Front Right Door Panel"': '"前门右内饰板"',
    '"Exhaust Pipes"': '"排气管"',
    '"Nitrous Oxide Bottle"': '"N2o瓶容量"',
    '"Nitrous Oxide Shot Size"': '"N2o喷射量"',
    '"Front Bumper Accessory"': '"前保险杠配件"',
    '"Stability Control"': '"稳定控制系统"',
    '"Traction Control"': '"牵引力控制系统"',
    '"Drive Modes"': '"驾驶模式"',
    '"Default Mode"': '"默认模式"',
    '"Drift Mode"': '"漂移模式"',
    '"Caged Mode"': '"限制模式"',
    '"Savage Mode"': '"极限性能模式"',
    '"Rear Seat Load"': '"后座装载"',
    '"Rear Hubcaps"': '"后轮毂盖"', #
    '"Left Antenna"': '"左侧天线"',
    '"Right Antenna"': '"右侧天线"',
    '"Front Bumper Support"': '"保险杠防撞梁"',
    '"Rear Fender Flares"': '"后轮眉"',
    '"Landau Top"': '"兰道车顶"',
    '"Rear Mudflaps"': '"后挡泥板"',
    '"Left Quarter Glass"': '"左侧后窗玻璃"',
    '"Right Quarter Glass"': '"右侧后窗玻璃"',
    '"Side Skirts"': '"侧裙"',
    '"Rear Fascia"': '"后饰板"',
    '"Under Glow Lights"': '"底盘灯"',
    '"Window Trim"': '"窗饰条"',
    '"Front Bumper Skirt"': '"保险杠前铲"',
    '"Gauge Cluster"': '"仪表盘"',
    '"Front Left Door Welding"': '"左前门焊死"',
    '"Front Right Door Welding"': '"右前门焊死"',
    '"Rear Left Door Welding"': '"左后门焊死"',
    '"Rear Right Door Welding"': '"右后门焊死"',
    '"Front Half Shafts"': '"前半轴"',
    '"Front Fascia"': '"前杠装饰件"',
    '"Concealed Flashers"': '"隐藏式闪光灯"',
    '"Front Grille"': '"前格栅"',
    '"Front Left Fender Liner"': '"左前翼子板内衬板"',
    '"Front Right Fender Liner"': '"右前翼子板内衬板"',
    '"Front Left Mudflap"': '"左前挡泥板"',
    '"Front Right Mudflap"': '"右前挡泥板"',
    '"Front Right Fender Trim"': '"右前翼子板装饰条"',
    '"Front Left Fender Trim"': '"左前翼子板装饰条"',
    '"Hood Bolts"': '"引擎盖螺栓"',
    '"Skidplate"': '"防护板"',
    '"Rear Transverse Leaf Spring"': '"后横向叶片簧"', #
    '"Beacon Light"': '"警示灯"',
    '"Left Door Glass"': '"左侧门玻璃"',
    '"Right Door Glass"': '"右侧门玻璃"',
    '"Left Door Panel"': '"左门内饰板"',
    '"Right Door Panel"': '"右门内饰板"',
    '"Front Left Inner Fender"': '"左前内翼子板"',
    '"Front Right Inner Fender"': '"右前内翼子板"',
    '"Front Fascia Signals"': '"前杠转向灯"',
    '"Rear Filler Panel"': '"后保险杠导流板"',
    '"Trunk Logo"': '"后备箱装饰标"',
    '"Radiator Support"': '"散热器框架"',
    '"Steering Box"': '"方向柱"',
    '"Rear Brake Shoes"': '"后轮刹车片"',
    '"Wheelie Bar"': '"防桥头尾架"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',
    # '"Hubcaps"': '"后轮毂盖"',

}
