translations = {
    '"Fuel Volume"': '"燃料箱"',
    '"Brake Force Multiplier"': '"制动力度"',
    '"Front/Rear Bias"': '"前后刹车分配"',
    '"Short Compression"': '"低速压缩行程"',
    '"Mid Compression"': '"中速压缩行程"',
    '"Long Compression"': '"高速压缩行程"',
    '"Short Rebound"': '"避震器低速回弹行程"',
    '"Long Rebound"': '"避震器高速回弹行程"',
    '"Compression damping"': '"压缩阻尼力度"',
    '"Rebound Damping"': '"回弹阻尼"',
    '"Setup-Specific Force Feedback Multiplier"': '"方向盘力反馈"',
    '"Bump Damping"': '"压缩阻尼"',
    '"Fast Bump Damping"': '"高速压缩阻尼"',
    '"Helper Spring Rate"': '"辅助弹簧硬度"',
    '"Fast Rebound Damping"': '"高速回弹阻尼"',
    '"Main Spring Rate"': '"主弹簧硬度"',
    '"Spring Height"': '"弹簧高度"',
    '"Final Drive Gear Ratio"': '"差速器齿比"',
    '"Anti-Roll Spring Rate"': '"防倾杆刚度"',
    '"Toe Left/Right Trim"': '"左右轮束脚"',
    '"Toe Adjust"': '"束脚"',
    '"Wheel Offset"': '"轮毂偏距"',
    '"Tire Ballast"': '"车轮负载"',
    '"Tire Pressure"': '"轮胎气压"',
    '"Minimum Gear"': '"N2o介入挡位"',
    '"Added Power"': '"N2o增压功率"',
    '"Minimum RPM"': '"N2o介入转速"',
    '"Camber Adjust"': '"前倾角"',
    '"Caster Adjust"': '"前束脚"',
    '"Base Torque Split"': '"加速扭矩分配"',
    '"Power Lock Rate"': '"减速扭矩锁定"',
    '"Pre-load Torque"': '"预加载扭矩"',
    '"RPM Limit Cut Time"': '"转速限制时间间隔"',
    '"RPM Limit"': '"转速限制"',
    '"Wastegate Pressure"': '"排气压力阀"',
    '"Spring Rate"': '"弹簧硬度"',
    '"1st Gear Ratio"': '"1档齿轮比"',
    '"2nd Gear Ratio"': '"2档齿轮比"',
    '"3rd Gear Ratio"': '"3档齿轮比"',
    '"4th Gear Ratio"': '"4档齿轮比"',
    '"5th Gear Ratio"': '"5档齿轮比"',
    '"6th Gear Ratio"': '"6档齿轮比"',
    '"Reverse Gear Ratio"': '"倒挡齿轮比"',
    '"Coast Lock Rate"': '"滑行减速齿比"',
    '"Forward Lock Rate"': '"前轴锁定齿比"',
    '"Turbo Boost Pressure"': '"涡轮增压压力"',
    '"Spring Collar Height"': '"弹簧底座高度"',
    '"Frame"': '"车架"',
    '"Brake Line Lock"': '"制动管路锁定"',
    '"Anti-Lock Braking System"': '"防抱死制动系统"',
    '"Rear Driveshaft"': '"后传动轴"',
    '"Left Fire Extinguisher"': '"左侧灭火器"',
    '"Right Fire Extinguisher"': '"右侧灭火器"',
    '"Floor Jack"': '"千斤顶"',
    '"GPS Antenna"': '"GPS天线"',
    '"Light Bar"': '"灯条"',
    '"Muffler"': '"消音器"',
    '"Number Plates"': '"车牌架"',
    '"Oil Bottles"': '"机油瓶"',
    '"Rear Frame"': '"后车架"',
    '"Taillight Bar"': '"尾灯条"',
    '"Tool Box"': '"工具箱"',
    '"Left Window Net"': '"左窗网"',
    '"Right Window Net"': '"右窗网"',
    '"Radiator"': '"散热器"',
    '"Front Bumper"': '"前保险杠"',
    '"Rear Bumper"': '"后保险杠"',
    '"Body"': '"车身"',
    '"Front License Plate"': '"前车牌"',
    '"Rear License plate"': '"后车牌"',
    '"Fuel Cell"': '"燃料电池"',
    '"License Plate Design"': '"车牌风格"',
    '"Paint Design"': '"涂装"',
    '"Glass Tint"': '"玻璃膜"',
    '"Navigation Unit"': '"导航设备"',
    '"Center High Mounted Stop Light"': '"尾部刹车灯"',
    '"Hood"': '"引擎盖"',
    '"Running Boards"': '"侧边脚踏"',
    '"Left Spotlight"': '"左探照灯"',
    '"Right Spotlight"': '"右探照灯"',
    '"Windshield"': '"挡风玻璃"',
    '"Interior Color"': '"内饰颜色"',
    '"Horn"': '"喇叭"',
    '"Front Left Door"': '"左车门"',
    '"Front Right Door"': '"右车门"',
    '"Front Left Door Detent"': '"左门限位器"',
    '"Front Right Door Detent"': '"右门限位器"',
    '"Dashboard"': '"仪表台"',
    '"Interior Accessories"': '"内饰配件"',
    '"Shifter"': '"挡杆"',
    '"Range Selector"': '"挡位选择器"',
    '"Steering Wheel"': '"方向盘"',
    '"Roof Accessory"': '"车顶配件"',
    '"Light Accessory"': '"灯配件"',
    '"Front Seat"': '"前排座椅"',
    '"Driver Seat"': '"驾驶座椅"',
    '"Passenger Seat"': '"副驾驶座椅"',
    '"Front Left Race Seat"': '"驾驶位赛车座椅"',
    '"Front Right Race Seat"': '"副驾驶赛车座椅"',
    '"Seat Color"': '"座椅颜色"',
    '"Front Left Fender"': '"左前翼子板"',
    '"Front Right Fender"': '"右前翼子板"',
    '"Grille Bars"': '"散热器格栅"',
    '"Left Headlight"': '"左侧大灯"',
    '"Right Headlight"': '"右侧大灯"',
    '"Front Left Signal"': '"前左转向灯"',
    '"Front Right Signal"': '"前右转向灯"',
    '"Front Suspension"': '"前悬挂系统"',
    '"Rear Suspension"': '"后悬挂系统"',
    '"Front Bump Stops"': '"前减震行程限位器"',
    '"Rear Bump Stops"': '"车牌架"',
    '"Front Driveshaft"': '"前传动轴"',
    '"Rear Shocks"': '"后减震器"',
    '"Front Shocks"': '"前减震器"',
    '"Rear Springs"': '"后悬挂弹簧"',
    '"Steering"': '"转向拉杆"',
    '"Front Sway Bar"': '"前防倾杆"',
    '"Rear Sway Bar"': '"后防倾杆"',
    '"Front Spindles"': '"前轮羊角"',
    '"Rear Spindles"': '"后轮羊角"',
    '"Front Brakes"': '"前刹车"',
    '"Rear Brakes"': '"后刹车"',
    '"Front Brake Pads"': '"前刹车片"',
    '"Rear Brake Pads"': '"后刹车片"',
    '"Front Differential"': '"差速器"',
    '"Rear Differential"': '"后差速器"',
    '"Front Axle Shafts"': '"前轴"',
    '"Front Final Drive"': '"前差速齿比"',
    '"Rear Final Drive"': '"后差速齿比"',
    '"Front Wheels"': '"前轮毂"',
    '"Rear Wheel"': '"后轮毂"',
    '"Front Tires"': '"前轮胎"',
    '"Rear Tires"': '"后轮胎"',
    '"Engine"': '"引擎"',
    '"Nitrous Oxide System"': '"一氧化二氮系统"',
    '"Engine Management"': '"行车电脑"',
    '"Engine Long Block"': '"引擎缸体"',
    '"Engine Mounts"': '"引擎机爪垫"',
    '"Intake"': '"进气系统"',
    '"Oil Pan"': '"油底壳"',
    '"Exhaust Manifold"': '"排气歧管"',
    '"Exhaust"': '"排气"',
    '"Transmission"': '"变速箱"',
    '"Torque Converter"': '"扭矩放大器"',
    '"Transfer Case"': '"传动分动箱"',
    '"Front Left Beacon Light"': '"前左侧警示灯"',
    '"Front Right Beacon Light"': '"前右侧警示灯"',
    '"Rear Left Beacon Light"': '"后左侧警示灯"',
    '"Rear Right Beacon Light"': '"后右侧警示灯"',
    '"Rear Left Bench"': '"左后座椅"',
    '"Rear Right Bench"': '"右后座椅"',
    '"Engine Cover"': '"引擎隔热罩"',
    '"Load"': '"装载"',
    '"Fuel Tank"': '"燃料箱"',
    '"Rear Cab Gate"': '"驾驶室隔断"',
    '"Left Mirror"': '"左后视镜"',
    '"Right Mirror"': '"右后视镜"',
    '"Front Left Quarter Glass"': '"前左侧小窗"',
    '"Front Right Quarter Glass"': '"前右侧小窗"',
    '"Left Running Board"': '"左侧脚踏板"',
    '"Right Running Board"': '"右侧脚踏板"',
    '"Rear Left Seat"': '"后排左侧座椅"',
    '"Rear Right Seat"': '"后排右侧座椅"',
    '"Front Siren"': '"前报警器"',
    '"Rear Siren"': '"后报警器"',
    '"Snorkel"': '"涉水喉"',
    '"Left Taillight"': '"左侧尾灯"',
    '"Right Taillight"': '"右侧尾灯"',
    '"Tire Pressure Management System"': '"胎压管理系统"',
    '"Rear License Plate"': '"后牌照架"',
    '"Left Auxilary Light"': '"左侧辅灯"',
    '"Right Auxilary Light"': '"右侧辅灯"',
    '"Left Light Cover"': '"左侧灯罩"',
    '"Right Light Cover"': '"右侧辅灯"',
    '"Chassis"': '"底盘"',
    '"Auxilary Fog Lights"': '"辅助雾灯"',
    '"Fog Light Covers"': '"辅助灯灯罩"',
    '"Rear Rear Differential"': '"尾轴差速器"',
    '"Rear Rear Final Drive"': '"尾轴差速器齿比"',
    '"Rev Limiter"': '"转速限制器"',
    '"Flywheel"': '"飞轮"',
    '"Propshaft"': '"传动轴"',
    '"Range Box"': '"分动箱"',
    '"Front Springs"': '"前弹簧"',
    '"Front Wheel Hubs"': '"前轮法兰盘"',
    '"Front Hubcaps"': '"前轮毂盖"',
    '"Rear Limit Straps"': '"后轴限位器"',
    '"Rear Rear Limit Straps"': '"尾轴限位器"',
    '"Rear Leaf Springs"': '"后板簧"',
    '"Rear Wheels"': '"后轮毂"',
    '"Rear Rear Brake Shoes"': '"尾轴刹车片"',
    '"Rear Tow Hitch"': '"后拖车钩"',
    '"Front Left Door Glass"': '"前左侧门玻璃"',
    '"Front Right Door Glass"': '"前右侧门玻璃"',
    '"Left Fuel Can Holder"': '"左侧燃油支架"',
    '"Left Fuel Can"': '"左侧燃油箱"',
    '"Right Fuel Can Holder"': '"右侧燃油支架"',
    '"Right Fuel Can"': '"右侧燃油箱"',
    '"Left Headlight Guard"': '"左侧大灯护罩"',
    '"Right Headlight Guard"': '"右侧大灯护罩"',
    '"Rear Door"': '"后门"',
    '"Rear Door Glass"': '"后门玻璃"',
    '"Spare Wheel"': '"备胎轮毂"',
    '"Spare Tire"': '"备胎"',
    '"Spare Wheel Cover"': '"备胎罩"',
    '"Body Accessory"': '"车身配件"',
    '"Front Rollcage Lights"': '"前辅灯"',
    '"Front Rollcage Roof Lights"': '"车顶辅灯"',
    '"Siren Audio"': '"警报类型"',
    '"Right Rear Door"': '"右后侧门"',
    '"Left Rear Door"': '"左后侧门"',
    '"Right Rear Door Glass"': '"右后侧门玻璃"',
    '"Left Rear Door Glass"': '"左后侧门玻璃"',
    '"Rear Rear Wheels"': '"尾轴轮毂"',
    '"Rear Rear Hubcaps"': '" 尾轴轮毂盖"',
    '"Front Seat Load"': '"副驾驶座椅装载"',
    '"Rear Rear Wheel Hubs"': '"尾轴轮毂法兰盘"',
    '"Rear Rear Shocks"': '"尾轴减震器"',
    '"Range Box Ratios"': '"分动箱齿轮比"', #
    '"Backlight"': '"后玻璃"',
    '"Driving & Safety Electronics"': '"车身稳定系统"',
    '"Lettering"': '"贴纸"',
    '"Roll Cage"': '"防滚架"',
    '"Rear Seats"': '"后排座椅"',
    '"Left Side Skirt"': '"左侧侧裙"',
    '"Right Side Skirt"': '"右侧侧裙"',
    '"Tow Hitch"': '"拖车钩"',
    '"Trim"': '"装饰条"',
    '"Trunk Load"': '"后备箱装载"',
    '"Undertray"': '"底部护板"',
    '"Interior Design"': '"内饰风格"',
    '"Front Splitter"': '"前唇"',
    '"Interior"': '"内饰"', #
    '"Center Console"': '"中控台"',
    '"Dashboard Accessory"': '"内饰配件"',
    '"Gauge"': '"仪表"',
    '"Shift Light"': '"换挡指示灯"',
    '"Front Left Fender Flare"': '"前左侧翼子板宽体"',
    '"Front Right Fender Flare"': '"前右侧翼子板宽体"',
    '"Grille"': '"散热格栅"',
    '"Grille Badge"': '"格栅标"',
    '"Quarter Panels"': '"后翼子板"', #
    '"Rear Left Fender Flare"': '"左后翼子板宽体"',
    '"Rear Right Fender Flare"': '"右后翼子板宽体"',
    '"Front Struts"': '"前减震器"',
    '"Rear Struts"': '"后减震器"',
    '"Power Steering"': '"转向助力系统"',
    '"Rear Subframe Mounts"': '"后元宝梁衬套"',
    '"Rear Halfshafts"': '"后半轴"',
    '"Front Halfshafts"': '"半轴"',
    '"Trunk"': '"后备箱"',
    '"Trunk Lettering"': '"后备箱字标"',
    '"Trunk Accessory"': '"后备箱配件"', #
    '"Rear Left Door"': '"左侧后门"',
    '"Rear Right Door"': '"右侧后门"',
    '"Rear Left Door Detent"': '"左后门限位器"',
    '"Rear Right Door Detent"': '"右后门限位器"',
    '"Rear Left Door Flare"': '"左后门翼子板"',
    '"Rear Right Door Flare"': '"右后门翼子板"',
    '"Rear Left Door Glass"': '"左后门玻璃"',
    '"Rear Right Door Glass"': '"右后门玻璃"',
    '"Rear Left Door Panel"': '"左后门内饰板"',
    '"Rear Right Door Panel"': '"右后门内饰板"',
    '"Exhaust Manifolds"': '"排气歧管"',
    '"Exhaust Mufflers"': '"排气消音器"',
    '"Spoiler"': '"尾翼"',
    '"Speed Limiter"': '"限速器"',
    '"Front Left Door Panel"': '"前门左内饰板"',
    '"Front Right Door Panel"': '"前门右内饰板"',
    '"Exhaust Pipes"': '"排气管"',
    '"Nitrous Oxide Bottle"': '"N2o瓶容量"',
    '"Nitrous Oxide Shot Size"': '"N2o喷射量"',
    '"Front Bumper Accessory"': '"前保险杠配件"',
    '"Stability Control"': '"稳定控制系统"',
    '"Traction Control"': '"牵引力控制系统"',
    '"Drive Modes"': '"驾驶模式"',
    '"Default Mode"': '"默认模式"',
    '"Drift Mode"': '"漂移模式"',
    '"Caged Mode"': '"限制模式"',
    '"Savage Mode"': '"极限性能模式"',
    '"Rear Seat Load"': '"后座装载"',
    '"Rear Hubcaps"': '"后轮毂盖"', #
    '"Left Antenna"': '"左侧天线"',
    '"Right Antenna"': '"右侧天线"',
    '"Front Bumper Support"': '"保险杠防撞梁"',
    '"Rear Fender Flares"': '"后轮眉"',
    '"Landau Top"': '"兰道车顶"',
    '"Rear Mudflaps"': '"后挡泥板"',
    '"Left Quarter Glass"': '"左侧后窗玻璃"',
    '"Right Quarter Glass"': '"右侧后窗玻璃"',
    '"Side Skirts"': '"侧裙"',
    '"Rear Fascia"': '"后饰板"',
    '"Under Glow Lights"': '"底盘灯"',
    '"Window Trim"': '"窗饰条"',
    '"Front Bumper Skirt"': '"保险杠前铲"',
    '"Gauge Cluster"': '"仪表盘"',
    '"Front Left Door Welding"': '"左前门焊死"',
    '"Front Right Door Welding"': '"右前门焊死"',
    '"Rear Left Door Welding"': '"左后门焊死"',
    '"Rear Right Door Welding"': '"右后门焊死"',
    '"Front Half Shafts"': '"前半轴"',
    '"Front Fascia"': '"前杠装饰件"',
    '"Concealed Flashers"': '"隐藏式闪光灯"',
    '"Front Grille"': '"前格栅"',
    '"Front Left Fender Liner"': '"左前翼子板内衬板"',
    '"Front Right Fender Liner"': '"右前翼子板内衬板"',
    '"Front Left Mudflap"': '"左前挡泥板"',
    '"Front Right Mudflap"': '"右前挡泥板"',
    '"Front Right Fender Trim"': '"右前翼子板装饰条"',
    '"Front Left Fender Trim"': '"左前翼子板装饰条"',
    '"Hood Bolts"': '"引擎盖螺栓"',
    '"Skidplate"': '"防护板"',
    '"Rear Transverse Leaf Spring"': '"后横向叶片簧"', #
    '"Beacon Light"': '"警示灯"',
    '"Left Door Glass"': '"左侧门玻璃"',
    '"Right Door Glass"': '"右侧门玻璃"',
    '"Left Door Panel"': '"左门内饰板"',
    '"Right Door Panel"': '"右门内饰板"',
    '"Front Left Inner Fender"': '"左前内翼子板"',
    '"Front Right Inner Fender"': '"右前内翼子板"',
    '"Front Fascia Signals"': '"前杠转向灯"',
    '"Rear Filler Panel"': '"后保险杠导流板"',
    '"Trunk Logo"': '"后备箱装饰标"',
    '"Radiator Support"': '"散热器框架"',
    '"Steering Box"': '"方向柱"',
    '"Rear Brake Shoes"': '"后轮刹车片"', #
    '"Wheelie Bar"': '"防桥头尾架"',
    '"Chrome Stripping"': '"镀铬装饰条"',
    '"Interior Accessory"': '"车内配件"',
    '"Front Seats"': '"前排座椅"',
    '"Taillights"': '"尾灯"',
    '"Rear Wheel Skirts"': '"后轮拱盖"',
    '"Front Left Door Trim"': '"左门装饰条"',
    '"Front Right Door Trim"': '"右门装饰条"',
    '"Front Left Fender Lettering"': '"左前翼子板字母标"',
    '"Front Right Fender Lettering"': '"右前翼子板字母标"',
    '"Hood Badge"': '"引擎盖徽标"',
    '"Front Brake Shoes"': '"前轮刹车片"',
    '"Trunk Floor"': '"行李厢底板"',
    '"Rear Left Quarter Glass"': '"左后侧小玻璃"',
    '"Rear Right Quarter Glass"': '"右后侧小玻璃"',
    '"Chassis Stiffening"': '"底盘加固"',
    '"Strut Bar"': '"顶巴"',
    '"Screen Branding"': '"后轮毂盖"',
    '"Tacho scale"': '"转速刻度表"',
    '"Speedo scale"': '"速度刻度表"',
    '"Exhaust Exit"': '"排气尾段"',
    '"Exhaust Tips"': '"排气口"',
    '"Left Tail Light"': '"左尾灯"',
    '"Right Tail Light"': '"右尾灯"',
    '"Roof"': '"车顶"',
    '"Roof Rack"': '"车顶行李架"',
    '"Roof Rack Accessory"': '"车顶行李架配件"',
    '"Middle Load"': '"中间负载"',
    '"Front Load"': '"前负载"',
    '"Rear Load"': '"后负载"',
    '"Cover"': '"盖子"',
    '"Tailgate"': '"尾门"',
    '"Tailgate Glass"': '"尾门玻璃"',
    '"Front Lip"': '"前铲"',
    '"Handbrake"': '"手刹车"',
    '"Padding"': '"握把"',
    '"Pedals"': '"踏板"',
    '"Pedal Pads"': '"踏板垫"',
    '"Clutch Pedal"': '"离合器踏板"',
    '"Clutch Pedal Pad"': '"离合器踏板垫"',
    '"Shift knob"': '"挡杆握把"',
    '"Shift Padding"': '"握把衬套"',
    '"Rear Left Door Fender Flare"': '"左后翼子板拓展件"',
    '"Rear Right Door Fender Flare"': '"右后翼子板拓展件"',
    '"Left Race Mirror"': '"左侧赛用后视镜"',
    '"Right Race Mirror"': '"右侧赛用后视镜"',
    '"Front Coilovers"': '"前避震器"',
    '"Rear Coilovers"': '"后避震器"',
    '"Rear Half Shafts"': '"后轮半轴"', #
    '"Rain Gutters"': '"挡雨槽"',
    '"Rear Glass"': '"后玻璃"',
    '"LED Lightbar"': '"LED灯条"',
    '"Gauges"': '"仪表"',
    '"Left Door"': '"左侧门"',
    '"Right"': '"右侧门"',
    '"Left Door Detent"': '"左门限位器"',
    '"Right Door Detent"': '"右门限位器"',
    '"Left Window Frame"': '"左侧车窗框架"',
    '"Right Window Frame"': '"右侧车窗框架"',
    '"Sun Strip"': '"遮阳条"',
    '"Front Subframe"': '"前副车架"',
    '"Rear Subframe"': '"后副车架"',
    '"Frunk Liner"': '"前备箱衬垫"',
    '"Nosecone Support"': '"前杠框架"',
    '"Nosecone"': '"前杠"',
    '"Rally Lights"': '"拉力灯组"',
    '"Front Right Nosecone Light"': '"前保险杠右侧辅灯"',
    '"Front Left Nosecone Light"': '"前保险杠左侧辅灯"',
    '"Front Hubs"': '"前轮毂"',
    '"Left Fuel Tank"': '"左侧油箱"',
    '"Right Fuel Tank"': '"右侧邮箱"',
    '"Transaxle"': '"变速箱"',
    '"Rear Left Quarter Panel"': '"左后侧车身板"',
    '"Rear Right Quarter Panel"': '"右后侧车身板"',
    '"Rear Left Inner Fender"': '"左后侧内轮拱"',
    '"Rear Right Inner Fender"': '"右后侧内轮拱"',
    '"Rear Hubs"': '"后轮毂"',
    '"Intake Scoops"': '"进气口"',
    '"Tailcone Support"': '"尾部支架"',
    '"Oil Cooler"': '"机油冷却器"',
    '"Tailcone"': '"尾部框架"',
    '"Rear Spoiler"': '"后尾翼"',
    '"Left Tailcone Light"': '"后杠左转向灯"',
    '"Right Tailcone Light"': '"后杠右转向灯"',
    '"Roof Panel"': '"车顶"',
    '"Passenger Seat Load"': '"副驾驶载物"',
    '"Rear Right Fender Signal"': '"右后侧翼子板信号灯"',
    '"Rear Left Fender Signal"': '"左后侧翼子板信号灯"',
    '"Rear Left Mudflap"': '"左后侧挡泥板"',
    '"Rear Right Mudflap"': '"右后侧挡泥板"', #
    '"Rear Body"': '"后车身"',
    '"Front Left Fender Signal"': '"左前翼子板信号灯"',
    '"Front Right Fender Signal"': '"右前翼子板信号灯"',
    '"Radiators"': '"散热器"',
    '"Front Left Undertray Panel"': '"前左侧底部护板"',
    '"Front Right Undertray Panel"': '"前右侧底部护板"',
    '"Center Undertray Panel"': '"中间底部护板"',
    '"Sun Visor"': '"遮阳板"',
    '"Sun Visors"': '"遮阳板"',
    '"Insulation and Accessories"': '"隔热材料和配件"',
    '"Front Left Door Fender Flare"': '"前左侧门翼子板扰流板"',
    '"Front Right Door Fender Flare"': '"前右侧门翼子板扰流板"',
    '"Right Door"': '"右侧门"',
    '"Front Right Side Marker"': '"前右侧信号灯"',
    '"Front Left Side Marker"': '"前左侧信号灯"',
    '"Front Bumper Badge"': '"前保险徽标"',
    '"Screen"': '"仪表屏幕"',
    '"Branding"': '"品牌"',
    '"Bottom Center"': '"底部中间"',
    '"Bottom Left"': '"底部左侧"',
    '"Bottom Right"': '"底部右侧"',
    '"Top Bar"': '"顶部"',
    '"Top Center"': '"顶部中间"',
    '"Top Left"': '"顶部左侧"',
    '"Top Right"': '"顶部右侧"',
    '"Top Left 1"': '"顶部左侧1"',
    '"Top Left 2"': '"顶部左侧2"',
    '"Top Left 3"': '"顶部左侧3"',
    '"Top Right 1"': '"顶部右侧1"',
    '"Top Right 2"': '"顶部右侧2"',
    '"Top Right 3"': '"顶部右侧3"',
    '"Race Mode"': '"赛道模式"',
    '"Left Fender Trim"': '"左侧翼子板饰条"',
    '"Right Fender Trim"': '"右侧翼子板饰条"',
    '"Front Left Fender Badge"': '"前左侧翼子板徽标"',
    '"Front Right Fender Badge"': '"前右侧翼子板徽标"',
    '"Front Rear Race Seat"': '"前排赛车座椅"',
    '"Rear Body Support"': '"后车身支撑"',
    '"Roof Bars"': '"车顶支架"',
    '"Roof Bars Load"': '"车顶支架装载"',
    '"Right Reverse Light"': '"尾部中间倒车灯"',
    '"Rear Left Marker Light"': '"左后侧标志灯"',
    '"Rear Right Marker Light"': '"右后侧标志灯"',
    '"Rear Fascia Lettering"': '"后保险杠字母标"',
    '"Rear Valance"': '"后扰流板"',
    '"Rear Brake Calipers"': '"后刹车卡钳"',
    '"Front Brake Calipers"': '"前刹车卡钳"',
    '"Left Fender"': '"左翼子板"',
    '"Right Fender"': '"右翼子板"',
    '"Front Side Marker Lights"': '"前侧信号灯"',
    '"Left Headlight Access Panel"': '"左前侧大灯面板"',
    '"Right Headlight Access Panel"': '"右前侧大灯面板"',
    '"Headliner"': '"车顶内衬"',
    '"Front Inner Fenders"': '"前内轮拱"',
    '"Front Strut Brace"': '"前顶巴"',
    '"2WD Mode"': '"后驱模式"',
    '"Sunroof Glass"': '"天窗玻璃"',
    '"Trim Lettering"': '"装饰条字母标"',
    '"Sideskirts"': '"侧裙"',
    '"Skid Plate"': '"护板"',
    '"Side Skid Plate"': '"侧护板"',
    '"Window Spoiler"': '"后窗扰流板"',
    '"Lights Color"': '"灯颜色"',
    '"Front Bumper Lights"': '"前保险杠辅灯"',
    '"Headlight Wipers"': '"大灯清洗"',
    '"Grille Lettering"': '"格栅字母标"',
    '"Hood Latch"': '"引擎盖锁"',
    '"Turn Signals"': '"转向灯"',
    '"TTSport Trunk Lettering"': '"TTSport后备箱字母标"', #
    '"Engine Cover Emblem"': '"发动机机盖徽标"',
    '"Badge"': '"车标"',
    '"Bottom Right 1"': '"底部右侧1"',
    '"Bottom Right 2"': '"底部右侧212"',
    '"Left Trunk light"': '"左侧后备箱灯"',
    '"Right Trunk light"': '"右侧后备箱灯"',
    '"Exhaust Grille"': '"排气格栅"',
    '"Intake Grille"': '"进气格栅"',
    '"Seat"': '"座椅"',
    '"Handlebar"': '"方向把手"',
    '"Spotlights"': '"探照灯"',
    '"Front Roof Panel"': '"前车顶"',
    '"Rear Roof Panel"': '"后车顶"',
    '"Left Side Panel"': '"左侧面板"',
    '"Right Side Panel"': '"右侧面板"',
    '"Hatch"': '"掀背门"',
    '"Left Side Window"': '"左侧车窗"',
    '"Right Side Window"': '"右侧车窗"',
    '"Rear Window"': '"后窗"',
    '"Roof Lights"': '"车顶灯"',
    '"Final Drive"': '"传动齿比"',
    '"Brakes"': '"刹车"',
    '"Reciever Hitch"': '"拖车连挂器"',
    '"Attachment"': '"附件"',
    '"Rear Wheel Hubs"': '"后轮轮毂"',
    '"Rear Wheelhubs"': '"后轮轮毂"',
    '"Cage"': '"防滚架"',
    '"Axle hubs"': '"车轴结构"',
    '"Front Wheelhubs"': '"后轮轮毂"',
    '"Middle Front Spindles"': '"前中部车轮轴"',
    '"Middle Front Tires"': '"前中部车轮轮胎"',
    '"Middle Front Wheels"': '"前中部车轮轮毂"',
    '"Middle Front Wheelshubs"': '"前中部车轮轮毂"',
    '"Middle Rear Wheelhubs"': '"中后部车轮"',
    '"Middle Rear Wheels"': '"中后部车轮轮毂"',
    '"Middle Rear Tires"': '"中后轮轮胎"',
    '"Rear Louvers"': '"后百叶窗"',
    '"Front Left Engine Bay Brace"': '"前左侧发动机舱支撑"',
    '"Front Right Engine Bay Brace"': '"前右侧发动机舱支撑"',
    '"Hood Lettering"': '"引擎盖字标"',
    '"Rear Bench Seats"': '"后排长座椅"',
    '"Front Subframe Brace"': '"前副车架支撑"',
    '"Quarter Panel Badges"': '"侧裙徽标"',
    '"Column Shifter"': '"方向盘挡杆1"',
    '"Rear Deck Accessory"': '"后备箱配件"',
    '"Rear Interior Panels"': '"后部内饰板"',
    '"Hydraulics Control Module"': '"液压控制模块"',
    '"Front Fender Lettering"': '"前翼子板字母标"',
    '"Side Trim"': '"侧面装饰条"',
    '"Front Left Window Frame"': '"前左侧车窗框架"',
    '"Front Right Window Frame"': '"前右侧车窗框架"',
    '"Front Bumper Guards"': '"前保险杠护板"',
    '"Rear Bumper Guards"': '"后保险杠护板"',
    '"Front Fascia Lettering"': '"前保险杠字母标"',
    '"Rear Links"': '"后部连杆"',
    '"Instrument Panel"': '"仪表盘"',
    '"Rear Window Bars"': '"后窗护栏"',
    '"Electronic Stability & Traction Control"': '"电控系统"',
    '"Reverse Warning Beeper"': '"倒车警报器"',
    '"Left Bed Accessory"': '"左侧货箱配件"',
    '"Right Bed Accessory"': '"右侧货箱配件"',
    '"Left Toolbox"': '"左侧工具箱"',
    '"Right Toolbox"': '"右侧工具箱"',
    '"Fender Lettering"': '"翼子板字母标"',
    '"Internal Roll Bar"': '"内部防滚架"',
    '"Internal Roll Bar (Black)"': '"黑色内部防滚架"',
    '"Internal Roll Bar (Body Colored)"': '"车身同色内部防滚架"',
    '"Rear Jump Seats"': '"后排折叠座椅"',
    '"Left Taillight Guard"': '"左侧尾灯保护罩"',
    '"Right Taillight Guard"': '"右侧尾灯保护罩"',
    '"Bed Accessory"': '"货箱配件"',
    '"Bed Cap Tailgate"': '"货箱盖尾门"',
    '"Left Bed Cap Glass"': '"货箱盖左侧玻璃"',
    '"Right Bed Cap Glass"': '"货箱盖右侧玻璃"',
    '"Front Left Door Handle"': '"前左侧门把手"',
    '"Front Right Door Handle"': '"前右侧门把手"',
    '"Antenna"': '"天线"',
    '"Hood Accessory"': '"引擎盖配件"',
    '"Police Radar"': '"警用对讲"',
    '"Spare Tire holder"': '"备用轮胎支架"',
    '"Rear Marker Lights"': '"后标志灯"',
    '"Tailgate Panel"': '"尾门面板"',
    '"Front Bumper Trim"': '"前保险杠装饰条"',
    '"Rear Bumper Trim"': '"后保险杠装饰条"',
    '"Rear Bumper Step"': '"后保险杠踏板"',
    '"Rear Towing Eyes"': '"后拖车钩"',
    '"Rear Towing Eyes (Black)"': '"黑色后拖车钩"',
    '"Rear Towing Eyes (Body Colored)"': '"车身同色后拖车钩"',
    '"Front Valance"': '"保险杠前裙"',
    '"Front Trim Ring"': '"前轮饰圈"',
    '"Rear Trim Ring"': '"后轮饰圈"',
    '"Fender Support"': '"翼子板框架"',
    '"Rear Bypass Shocks"': '"后避震器旁通阀"',
    '"Rear Left Door Handle"': '"后左侧门把手"',
    '"Rear Right Door Handle"': '"后右侧门把手"',
    '"Bed"': '"货箱"',
    '"Bed Trim"': '"货箱装饰条"',
    '"Front Bumper Bar"': '"前杠防撞梁"',
    '"Rear Bumper Bar"': '"后杠防撞梁"',
    '"Front Air Dam"': '"保险杠前唇"',
    '"Fog Lights"': '"雾灯"',
    '"Police Laptop"': '"警用电脑"',
    '"Driver Armrest"': '"驾驶扶手"',
    '"Passenger Armrest"': '"副驾驶扶手"',
    '"ESC & TC"': '"电控系统"',
    '"Front Right Side Door"': '"前右侧车门"',
    '"Front Left Side Door"': '"前左侧车门"',
    '"Front Left Side Door Glass"': '"前左侧门玻璃"',
    '"Front Right Side Door Glass"': '"前右侧门玻璃"',
    '"Front Door Lettering"': '"前车门字母标"',
    '"Inner Fenders"': '"翼子板内衬"',
    '"Air Conditioning Unit"': '"空调单元"',
    '"Radio"': '"收音机"',
    '"Left Rear Door Lettering"': '"左后车门字母标识"',
    '"Right Rear Door Lettering"': '"右后车门字母标识"',
    '"Left Rear Door Panel"': '"左后车门面板"',
    '"Right Rear Door Panel"': '"右后车门面板"',
    '"Roof Liner"': '"车顶内衬"',
    '"Front Right Side Door Panel"': '"前右侧车门面板"',
    '"Bull Bar Accessory"': '"前杠配件"',
    '"Muffler Tips"': '"排气管尾端"',
    '"Rear Right Side Door"': '"右后侧车门"',
    '"Front Left Bumper Signal"': '"前左侧保险杠转向灯"',
    '"Front Right Bumper Signal"': '"前右侧保险杠转向灯"',
    '"Left Fog Light"': '"左侧雾灯"',
    '"Right Fog Light"': '"右侧雾灯"',
    '"Low Range Selector"': '"低速挡选择器"',
    '"Tailgate Lettering"': '"尾门字母标"',
    '"Fascia Accessory"': '"保险杠装饰配件"',
    '"Cargo Basket Lights"': '"货架灯"',
    '"Front Cargo"': '"前部货物"',
    '"Middle Cargo"': '"中部货物"',
    '"Rear Cargo"': '"后部货物"', #
    '"Front Frame"': '"车架前部分"',
    '"Chicken Lights"': '"前杠辅助灯"',
    '"Design"': '"涂装"',
    '"Sleeper"': '"卧铺"',
    '"Sleeper Accessory"': '"卧铺配件"',
    '"Left Storage Compartment Door"': '"左侧储物舱门"',
    '"Left Sleeper Door"': '"左侧卧铺门"',
    '"Right Sleeper Door"': '"右侧卧铺门"',
    '"Right Storage Compartment Door"': '"右侧储物舱门"',
    '"Mattress"': '"床垫"',
    '"Upper Mattress"': '"上层床铺"',
    '"Front Left Sleeper Glass"': '"前左侧卧铺窗玻璃"',
    '"Front Right Sleeper Glass"': '"前右侧卧铺窗玻璃"',
    '"Left Sleeper Glas"': '"左侧卧铺窗玻璃"',
    '"Right Sleeper Glas"': '"右侧卧铺窗玻璃"',
    '"Cab"': '"驾驶室"',
    '"Visor"': '"遮阳板"',
    '"Beacon Lights"': '"警示灯"',
    '"Left Horn"': '"左喇叭"',
    '"Right Horn"': '"右喇叭"',
    '"Left Windshield"': '"左侧挡风玻璃"',
    '"Right Windshield"': '"右侧挡风玻璃"',
    '"Cab Trim"': '"驾驶室装饰条"',
    '"Left Mirror Antenna"': '"左侧后视镜天线"',
    '"Right Mirror Antenna"': '"右侧后视镜天线"',
    '"Right Lower Door Glass"': '"右侧下门玻璃"',
    '"Left Lower Door Glass"': '"左侧下门玻璃"',
    '"CB Radio"': '"CB电台"',
    '"Dashboard Material"': '"仪表材质"',
    '"Air Suspension Gauge"': '"空气悬挂压力表"',
    '"Boost Gauge"': '"增压表"',
    '"Compression Brake Switch"': '"压缩刹车开关"',
    '"Interaxle Differential Lock Switch"': '"车轴间差速锁开关"',
    '"Fifth Wheel Slider Lock Switch"': '"转向轮滑锁开关"',
    '"High Idle Switch"': '"高怠速开关"',
    '"Anniversary Plaque"': '"纪念牌"',
    '"PTO Controls"': '"动力输出轴控制"',
    '"Low Air Warning"': '"低气压警告"',
    '"Hood & Fenders"': '"引擎盖和翼子板"',
    '"Hood Badges"': '"引擎盖徽标"',
    '"Front Left Turn Signal"': '"前左转向灯"',
    '"Front Right Turn Signal"': '"前右转向灯"',
    '"Left Headlight Design"': '"左侧大灯设计"',
    '"Right Headlight Design"': '"右侧大灯设计"',
    '"Left Headlight Visor"': '"左侧大灯遮阳板"',
    '"Right Headlight Visor"': '"右侧大灯遮阳板"',
    '"Air Filter Bracket"': '"空滤支架"',
    '"Left Air Filter"': '"左侧空滤"',
    '"Right Air Filter"': '"右侧空滤"',
    '"Grille Insert"': '"进气格栅"',
    '"Air Compressor"': '"空气压缩机"',
    '"Hydraulic Pump"': '"液压泵"',
    '"Left Fuel Tank Strap Design"': '"左侧油箱固定带设计"',
    '"Right Fuel Tank Strap Design"': '"右侧油箱固定带设计"',
    '"Left Fuel Tank Design"': '"左侧油箱设计"',
    '"Right Fuel Tank Design"': '"右侧油箱设计"',
    '"Left Exhaust Stack"': '"左侧排气管"',
    '"Right Exhaust Stack"': '"右侧排气管"',
    '"Left Side Step"': '"左侧踏板"',
    '"Right Side Step"': '"右侧踏板"',
    '"Air Tanks"': '"储气罐"',
    '"Frame Ending"': '"尾端车架"',
    '"Pintle Hitch"': '"钩式拖车挂钩"',
    '"Tail Light Mount"': '"尾灯支架"',
    '"License Plate"': '"车牌"',
    '"Tail Lights"': '"尾灯"',
    '"Upfit"': '"额外配置"',
    '"Fifth Wheel Plate"': '"挂车牵引座"',
    '"Headache Rack"': '"防撞架"',
    '"Rear Air Brake control Valve"': '"后气刹控制阀"',
    '"Rear Mud Flaps"': '"后挡泥板"',
    '"Rear Springs & Airbags"': '"后悬挂与气囊"',
    '"Rear Rear Springs & Airbags"': '"尾部悬挂与气囊"',
    '"Front Rear Spindles"': '"前部后车轮轴"',
    '"Rear Rear Spindles"': '"尾部车轮周轴"',
    '"Rear Rear Brakes"': '"尾部刹车"',
    '"Rear Rear Tires"': '"尾部轮胎"',
    '"Interaxle Differential"': '"车轴间差速器"',
    '"Inter Axle Driveshaft"': '"后轴间传动轴"',
    '"Front Axle"': '"前车轴"',
    '"Wing Finish Type"': '"扰流板类型"',
    '"Air Tank"': '"储气罐"',
    '"Cab Struts"': '"驾驶室支撑杆"',
    '"Left Hand Rail"': '"左侧扶手"',
    '"Right Hand Rail"': '"右侧扶手"',
    '"Side Badges"': '"侧面徽标"',
    '"Left Step"': '"左侧踏板"',
    '"Right Step"': '"右侧踏板"',
    '"Plaque"': '"铭牌"',
    '"Shift Pattern Plaque"': '"挡位铭牌"',
    '"Compression Brake Controls"': '"压缩刹车控制"',
    '"High Idle Controls"': '"高怠速控制"',
    '"Heater"': '"加热器"',
    '"Right Door Foot Glass"': '"右侧门脚部玻璃"',
    '"Grille Insert Design"': '"进气格栅设计"',
    '"Grille Frame Design"': '"进气格栅框架设计"',
    '"Exhaust and Intake Mount"': '"排气和进气支架"',
    '"Right Exhaust Tips"': '"右侧排气尾管"',
    '"Right Exhaust Flap"': '"右侧排气阀"',
    '"Right Muffler"': '"右侧消声器"',
    '"Right Heatshield"': '"右侧隔热罩"',
    '"Left Intake Snorkel"': '"左侧进气喉管"',
    '"Steps"': '"侧踏板"',
    '"Tanker Livery"': '"罐体涂装"',
    '"Main Pipes"': '"主管道"',
    '"Left Pipes"': '"左侧管道"',
    '"Side Box"': '"侧边箱"',
    '"Left Wheel Well"': '"左侧轮胎拱"',
    '"Right Wheel Well"': '"右侧轮胎拱"',
    '"Leaf Springs"': '"板簧"',
    '"Axles"': '"车轴"', #
    '"Left Flag Pole"': '"左侧旗杆"',
    '"Right Flag Pole"': '"右侧旗杆"',
    '"Rear Guard"': '"后防护"',
    '"Rear Guard Lights"': '"后护板灯"',
    '"Rear Shock Reservoirs"': '"后减震储液罐"',
    '"Left Rock Slider"': '"左侧岩石护杠"',
    '"Right Rock Slider"': '"右侧岩护杠"',
    '"Third Brake Light"': '"高位刹车灯"',
    '"Rear Left Fender"': '"左后翼子板"',
    '"Rear Right Fender"': '"右后翼子板"',
    '"Spare Tire Mount"': '"备胎支架"',
    '"Front Left Foglight"': '"左前雾灯"',
    '"Front Right Foglight"': '"右前雾灯"',
    '"Clutches"': '"离合器"',
    '"Left Flag"': '"左边旗"',
    '"Right Flag"': '"右边旗"',
    '"Front Guard"': '"前防护装置"',
    '"Front Spoiler"': '"前扰流板"',
    '"Front Steering"': '"转向系统"',
    '"Steering Column"': '"转向柱"', #
    '"Rear Bumper Support"': '"后杠防撞梁"',
    '"Engine Lid"': '"引擎舱盖"',
    '"Front Left Lip"': '"左导流板"',
    '"Front Right Lip"': '"右导流板"',
    '"Frunk Load"': '"前备厢装载"',
    '"Left Taillight Panel"': '"左侧尾灯面板"',
    '"Right Taillight Panel"': '"右侧尾灯面板"',
    '"Left Taillight Panel (Black)"': '"左侧尾灯面板（黑色）"',
    '"Right Taillight Panel (Black)"': '"右侧尾灯面板（黑色）"',
    '"Parking Brake"': '"手刹车"',
    '"Rear Diffuser"': '"后扰流板"',
    '"Sideskirt Lip"': '"侧裙唇"',
    '"Roof Spoiler"': '"车顶扰流板"',
    '"Body Trim"': '"车身饰条"',
    '"Drag Controls"': '"空气动力套件拖拽控制"',
    '"Racing Parts Color"': '"赛车部件颜色"',
    '"Hydraulic Handbrake"': '"液压手刹"',
    '"Front Left Seat"': '"左前座椅"',
    '"Front Right Seat"': '"右前座椅"',
    '"Front Badge"': '"前车标"',
    '"Left Signal"': '"左侧转向灯"',
    '"Right Signal"': '"右侧转向灯"', #
    '"Rear Bash Bar"': '"后防撞梁"',
    '"Front Canards"': '"前杠风刀"',
    '"Left Headlight Shade"': '"左侧大灯遮罩"',
    '"Right Headlight Shade"': '"右侧大灯遮罩"',
    '"Rear Left Marker"': '"左后示宽灯"',
    '"Rear Right Marker"': '"右后示宽灯"',
    '"Package Shelf"': '"后置物挡板"',
    '"Front Left Marker"': '"前左侧示宽灯"',
    '"Front Right Marker"': '"前右侧示宽灯"',
    '"Left Trunk Taillight"': '"左侧后备箱灯"',
    '"Right Trunk Taillight"': '"右侧后备箱灯"',
    '"Trunk Panel Lettering"': '"后备箱字母标"',
    '"Fuel Tanks"': '"燃料箱"',
    '"Rear Strut Brace"': '"后顶巴"',
    '"Lights"': '"灯光"',
    '"Logo"': '"车标"',
    '"Right Fender Signal"': '"翼子板转向灯"',
    '"Firewall Glass"': '"防火墙玻璃"',
    '"Left Seat"': '"左侧座椅"',
    '"Right Seat"': '"右侧座椅"',
    '"Lower Spoiler"': '"下扰流板"',
    '"Sunstrip"': '"遮阳条"',
    '"Bumper Grille"': '"保险杠格栅"',
    '"Bumper Trim"': '"保险杠装饰条"',
    '"Intake & Exhaust"': '"进气和排气"',
    '"Left Fender Signal"': '"左翼子板转向灯"',
    '"Intake Pipe"': '"进气管"',
    '"Exhaust Downpipe"': '"排气管"',
    '"Front Transfercase"': '"前分动箱"',
    '"Body Lettering"': '"车身字母标"',
    '"Trunk Mounted Spare"': '"后备箱备胎"',
    '"Spare Oil Bottles"': '"机油瓶"',
    '"Spare Tire Holder"': '"备胎支架"',
    '"Windshield Glass"': '"挡风玻璃"',
    '"Windshield Latch"': '"挡风玻璃扣具"',
    '"Windshield Bar"': '"前挡顶部灯具"',
    '"Windshield Bar Accessory"': '"前挡灯具配件"',
    '"Cover Design"': '"灯罩"',
    '"Center Skid Plate"': '"中间底部护板"',
    '"Spare Driveshaft"': '"备用传动轴"',
    '"Front Left Door Cover"': '"前左车门覆盖件"',
    '"Front Right Door Cover"': '"前右车门覆盖板"',
    '"Soft Top/Roll Bar Padding Color"': '"软顶支架颜色"',
    '"Roll Bar Padding"': '"软顶支架"',
    '"Front Roll Bar"': '"前软顶支架"',
    '"Side Windows"': '"侧窗"',
    '"Rear Seats Load"': '"后座装载"',
    '"Windshield Frame"': '"挡风玻璃框架"',
    '"Left Door Mirror"': '"左侧车门后视镜"',
    '"Right Door Mirror"': '"右侧车门后视镜"',
    '"Left Fender Mirror"': '"左翼子板后视镜"',
    '"Right Fender Mirror"': '"右翼子板后视镜"',
    '"Bumper Rally Lower Lights"': '"保险杠拉力赛下灯"',
    '"Bumper Rally Upper Lights"': '"保险杠拉力赛上灯"',
    '"Sound Deadening and Accessories"': '"隔音材料及配件"',
    '"Front Left Fog Light"': '"前左雾灯"',
    '"Front Right Fog Light"': '"前右雾灯"',
    '"Grille Flashers"': '"进气格栅闪光灯"',
    '"Left Headlight Decal"': '"左前灯装饰贴"',
    '"Right Headlight Decal"': '"右前灯装饰贴"',
    '"Trunk Trim"': '"后备箱装饰条"',
    '"Turbo Exhaust"': '"涡轮增压"',
    '"Push Bar"': '"推杠"',
    '"Dashboard Accessories"': '"仪表配件"',
    '"Oilpan"': '"油底壳"', #
    '"Trunk Lights"': '"后备箱灯"',
    '"Bed Contents"': '"货箱内物品"',
    '"Bin"': '"收纳箱"',
    '"Left Stabilizer"': '"左侧辅助轮"',
    '"Right Stabilizer"': '"右侧辅助轮"',
    '"Front Grille Badge"': '"前格栅标志"',
    '"Passenger Weight"': '"副驾驶质量"',
    '"Driver Weight"': '"驾驶质量"',
    '"Front Coilover"': '"前减震器"',
    '"Front Spindle"': '"前主轴"',
    '"Front Wheel"': '"前轮毂"',
    '"Front Tire"': '"前轮胎"',
    '"Front Fender Flares"': '"前翼子板轮眉"',
    '"Bed Box Tailgate"': '"货箱尾门"', #
    '"Rear Tow Hook"': '"后拖车钩"',
    '"Airdam"': '"前铲"',
    '"Canopy"': '"顶棚"',
    '"Left Side Cargo"': '"左侧储物"',
    '"Right Side Cargo"': '"右侧储物"',
    '"Cargo Tray"': '"行李托板"',
    '"Left Mudflap"': '"左挡泥板"',
    '"Right Mudflap"': '"右挡泥板"',
    '"Reverse Light"': '"倒车灯"',
    '"Rear Left Signal"': '"后左侧转向灯"',
    '"Rear Right Signal"': '"后右侧转向灯"',
    '"Gas Strut"': '"支撑杆"',
    '"Front Tow Hook"': '"前拖车钩"',
    '"3rd Row Seats"': '"第三排座椅"',
    '"Lightbar Controls"': '"灯条控制"',
    '"Stereo"': '"音响系统"',
    '"2nd Row Left Seat"': '"第二批左侧座椅"',
    '"2nd Row Right Seat"': '"第二批右侧座椅"',
    '"Rear Bumper Lip"': '"后保险杠下沿"',
    '"Side Lettering"': '"侧面文字"',
    '"Radiator Cover"': '"散热器罩"',
    '"Lightbar"': '"灯条"',
    '"Roof Rails"': '"车顶支架"',
    '"Center Stop Light"': '"尾部刹车灯"',
    '"Extra Lettering"': '"额外标识"',
    '"Displacement Lettering"': '"排量标识"',
    '"Nameplate Lettering"': '"Sport标识"',
    '"Trim Level Lettering"': '"配置标识"',
    '"Rear Step"': '"后踏板"',
    '"Tailgate Trim"': '"尾门装饰条"',
    '"Tailgate Struts"': '"尾门支撑杆"',
    '"Spoiler Extension"': '"扰流板延申"',
    '"2nd Row Seats"': '"第二排座椅"',
    '"Quarter Panel Lettering"': '"翼子板字母标"',
    '"Climate Control Unit"': '"空调控制单元"',
    '"Console Shifter"': '"中控换挡杆"',
    '"Left Door Welding"': '"左门焊死"',
    '"Right Door Welding"': '"右门焊死"',
    '"Front Fascia Badge"': '"前杠标志"',
    '"Rear Fascia Badge"': '"后杠标志"',
    '"Rear Lettering"': '"后部字母标"',
    '"Hood Lights"': '"引擎盖灯"',
    '"Splitter"': '"前铲"',
    '"Front Left Splitter Panel"': '"左前扰流板"',
    '"Front Right Splitter Panel"': '"右前扰流板"',
    '"Hood Panel"': '"引擎盖"',
    '"Jack"': '"千斤顶"',
    '"Roof Light Bar"': '"车顶灯组"',
    '"Left Bed Side Panel"': '"左侧货箱侧板"',
    '"Right Bed Side Panel"': '"右侧货箱侧板"',
    '"Gear Reduction"': '"减速器"',
    '"V8 Exhaust"': '"V8排气系统"',
    '"Spare Wheel Mounts"': '"备胎支架"',
    '"Left Spare Tire"': '"左备胎"',
    '"Right Spare Tire"': '"右备胎"',
    '"Left Spare Wheel"': '"左备胎轮毂"',
    '"Right Spare Wheel"': '"右备胎轮毂"',
    '"Left Spare Wheel Holder"': '"左侧备用轮圈支架"',
    '"Right Spare Wheel Holder"': '"右侧备用轮圈支架"',
    '"Front Air Bumpstop"': '"前气动限位器"',
    '"Front Air Bump Stop"': '"前气动限位器"',
    '"Front Bypass Shocks"': '"前双筒式负压避震器"',
    '"Rear Air Bumpstop"': '"后气动限位器"',
    '"Fire Extinguisher"': '"灭火器"',
    '"Headlights"': '"前大灯"',
    '"Roof Lightbar"': '"车顶灯条"',
    '"Roof Panels"': '"车顶板"',
    '"Tailights"': '"尾灯"',
    '"Passenger Display Screen"': '"副驾驶显示屏"',
    '"Front Left offroad Seat"': '"前左越野座椅"',
    '"Front Right offroad Seat"': '"前右越野座椅"',
    '"Front Left Offroad Racing Seat"': '"前左越野赛车座椅"',
    '"Front Right Offroad Racing Seat"': '"前右越野赛车座椅"',
    '"Front Left Offroad Race Seat Base"': '"前左越野赛车座椅底座"',
    '"Front Right Offroad Race Seat Base"': '"前右越野赛车座椅底座"',
    '"Spare Wheel Mount"': '"备用轮胎支架"',
    '"Destination Signs Type"': '"LDE显示屏类型"',
    '"Safety Interlock"': '"安全联锁装置"',
    '"Front Airbags"': '"前气囊"',
    '"Rear Axle"': '"后轴"',
    '"Rear Airbags"': '"后气囊"',
    '"Front Access Panel"': '"前部检修盖板"',
    '"Rear Access Panel"': '"后部检修面板"',
    '"Front Left Access Panel"': '"前左侧检修盖板"',
    '"Rear Left Access Panel"': '"后左侧检修盖板"',
    '"Rear Right Access Panel"': '"后右侧检修面板"',
    '"Ad Carriers"': '"广告贴"',
    '"Left Advertisement"': '"左侧广告"',
    '"Right Advertisement"': '"右侧广告"',
    '"Rear Advertisement"': '"后部广告"',
    '"Advertisement"': '"广告"',
    '"Engine Air Filter"': '"引擎空滤器"',
    '"Engine Exhaust"': '"引擎排气"',
    '"Glass"': '"玻璃"',
    '"Interior Mirror"': '"车内后视镜"',
    '"Front Side Door"': '"前门"',
    '"Rear Side Door"': '"后门"',
    '"Rear Destination Sign"': '"后部LED屏"',
    '"Side Destination Sign"': '"侧面LED屏"',
    '"Engine Access Panel"': '"引擎维修盖板"',
    '"Passenger Seats"': '"乘客座椅"',
    '"Interior Hand Rails"': '"内部扶手"',
    '"Passenger Information Displays"': '"车内显示屏"',
    '"Front Destination Sign"': '"前部LED屏"', #
    '"Trailer Suspension"': '"拖车悬挂系统"',
    '"Tandem Leaf Springs"': '"双联叶片弹簧"',
    '"Container Branding"': '"集装箱品牌"',
    '"Trailer Legs"': '"拖车支腿"',
    '"Middle Retract Bolsters"': '"中间固定底座"',
    '"Front Retract Container Pins"': '"前部固定销"',
    '"Middle Retract Container Pins"': '"中部固固定销"',
    '"Rear Retract Container Pins"': '"后部固定销"',
    '"Bogie"': '"车轴组"',
    '"Locking System"': '"锁定系统"',
    '"Wires"': '"电线"',
    '"D-Rings"': '"D型拖环"',
    '"D-Ring"': '"D型拖环"',
    '"Mud Flaps"': '"挡泥板"',
    '"Rear Retract Bolsters"': '"尾部固定底座"',
    '"Suspension"': '"悬挂系统"',
    '"Brake Valve"': '"刹车阀"',
    '"First Axle Tires"': '"第一轴轮胎"',
    '"Second Axle Tires"': '"第二轴轮胎"',
    '"Third Axle Tires"': '"第三轴轮胎"',
    '"Default Configuration"': '"配置"',
    '"Front Container"': '"前部集装箱"',
    '"Rear Container"': '"后部集装箱"',
    '"Top Couplers"': '"上部连结装置"',
    '"Ladder"': '"悬梯"',
    '"Front Lid"': '"前盖板"',
    '"Spill Box Covers"': '"箱体顶盖"',
    '"Walking Grid"': '"步行格栅"',
    '"Straps"': '"绑带"',
    '"Fabric type"': '"面料类型"',
    '"Container"': '"集装箱"',
    '"Doors"': '"门"',
    '"Extra Top Container"': '"集装箱顶部叠放"',
    '"Fifth Wheel"': '"挂车牵引座"',
    '"Dry Van Trailer"': '"厢式货车拖车"',
    '"Side Marker Lights"': '"侧标灯"',
    '"Front Wall"': '"前挡板"',
    '"Bogie Rail"': '"转向架导轨"',
    '"First Axle Brakes"': '"第一轴刹车"',
    '"Second Axle Brakes"': '"第二轴刹车"',
    '"Third Axle Brakes"': '"第三轴刹车"',
    '"First Axle Wheels"': '"第一轴轮毂"',
    '"Second Axle Wheels"': '"第二轴轮毂"',
    '"Third Axle Wheels"': '"第三轴轮毂"',
    '"First Axle Spindles"': '"第一轴主轴"',
    '"Second Axle Spindles"': '"第二主轴"',
    '"Third Axle Spindles"': '"第三主轴"',
    '"Loading Ramp"': '"装卸坡道"',
    '"Underride Guard"': '"防护栏"',
    '"Side Door"': '"侧门"',
    '"Flatbed Trailer"': '"平板拖车"',
    '"Landing Gear"': '"拖车支腿"',
    '"Storage Box"': '"储物箱"',
    '"Bogie Style"': '"转向架类型"',
    '"Side Lights"': '"侧灯"',
    '"Chains and Straps"': '"链条绑带"',
    '"Frameless Dump Trailer"': '"无框架自卸拖车"',
    '"Marker Lights"': '"标志灯"',
    '"Draft Arms"': '"拖臂"',
    '"Kingpin Plate"': '"主销"',
    '"Hydraulics"': '"液压装置"',
    '"Hydraulics Source"': '"液压供应座"',
    '"Axle Layout"': '"轴布局配置"',
    '"Rear Bolsters"': '"后支撑架"',
    '"Front Bolster Lights"': '"前支撑架灯"',
    '"Front Log 1"': '"前装载1"',
    '"Front Log 2"': '"前装载2"',
    '"Front Log 3"': '"前装载3"',
    '"Front Log 4"': '"前装载4"',
    '"Front Log 5"': '"前装载5"',
    '"Front Log 6"': '"前装载6"',
    '"Rear Log 1"': '"后装载1"',
    '"Rear Log 2"': '"后装载2"',
    '"Rear Log 3"': '"后装载3"',
    '"Rear Log 4"': '"后装载4"',
    '"Rear Log 5"': '"后装载5"',
    '"Rear Log 6"': '"后装载6"',
    '"Front Straps"': '"前绑带"',
    '"Rear Straps"': '"后绑带"',
    '"Wood Species"': '"木材种类"',
    '"Ramp Door"': '"坡道"',
    '"Springs"': '"弹簧"',
    '"Spindles"': '"支撑轴头"',
    '"Wheels"': '"轮子"',
    '"Front Left Wheel Well"': '"前左轮拱"',
    '"Front Right Wheel Well"': '"前右轮拱"',
    '"Rear Left Wheel Well"': '"后左轮拱"',
    '"Rear Right Wheel Well"': '"后右轮拱"',
    '"Deck"': '"平板"',
    '"Lift Hydraulics"': '"升降液压系统"',
    '"Bumper"': '"保险杠"',
    '"Front Attachment"': '"前部附件装置"',
    '"Middle Spindles"': '"中主轴"',
    '"Middle Brakes"': '"中轴刹车"',
    '"Middle Wheels"': '"中轴轮"',
    '"Middle Tires"': '"中轴轮胎"',
    '"Dolly Type"': '"小拖车"',
    '"Air Conditioner"': '"空调"',
    '"Propane Tanks"': '"丙烷罐"',
    '"Rock Guard"': '"防护遮板"',
    '"Tanker Trailer"': '"罐式拖车"',
    # ------------------------------------------------------------------
}
