# translations = {
#     "Fuel Volume": "燃料箱",
#     "Brake Force Multiplier": "制动力度",
#     "Front/Rear Bias": "前后刹车分配",
#     "Short Compression": "低速压缩行程",
#     "Mid Compression": "中速压缩行程",
#     "Long Compression": "高速压缩行程",
#     "Short Rebound": "避震器低速回弹行程",
#     "Long Rebound": "避震器高速回弹行程",
#     "Compression damping": "压缩阻尼",
#     "Rebound Damping": "回弹阻尼",
#     "Setup-Specific Force Feedback Multiplier": "方向盘力反馈",
#     "Bump Damping": "压缩阻尼",
#     "Fast Bump Damping": ''"高速压缩阻尼"'',
#     "Helper Spring Rate": '"辅助弹簧硬度"',
#     "Fast Rebound Damping": '"高速回弹阻尼"',
#     "Main Spring Rate": '"主弹簧硬度"',
#     "Spring Height": '"弹簧高度"',
#     "Final Drive Gear Ratio": '"差速器齿比"',
#     "Anti-Roll Spring Rate": '"防倾杆刚度"',
#     "Toe Left/Right Trim": '"左右轮束脚"',
#     "Toe Adjust": '"束脚"',
#     "Wheel Offset": '"轮毂偏距"',
#     "Tire Ballast": '"车轮负载"',
#     "Tire Pressure": '"轮胎气压"',
#     "Minimum Gear": '"N2o介入挡位"',
#     "Added Power": '"N2o增压功率"',
#     "Minimum RPM": '"N2o介入转速"',
#     "Camber Adjust": '"前倾角"',
#     "Caster Adjust": '"前束脚"',
#     "Base Torque Split": '"加速扭矩分配"',
#     "Power Lock Rate": '"减速扭矩锁定"',
#     "Pre-load Torque": '"预加载扭矩"',
#     "RPM Limit Cut Time": '"转速限制时间间隔"',
#     "RPM Limit": "转速限制"',
#     "Wastegate Pressure": '"排气压力阀"',
#     "Spring Rate": '"弹簧硬度"',
#     "1st Gear Ratio": '"1档齿轮比"',
#     "2nd Gear Ratio": '"2档齿轮比"',
#     "3rd Gear Ratio": '"3档齿轮比"',
#     "4th Gear Ratio": '"4档齿轮比"',
#     "5th Gear Ratio": '"5档齿轮比"',
#     "6th Gear Ratio": '"6档齿轮比"',
#     "Reverse Gear Ratio": '"倒挡齿轮比"',
#     "Coast Lock Rate": '"滑行减速齿比"',
#     "Forward Lock Rate": '"前轴锁定齿比"',
#
#
#
#     # 你可以在这里添加更多的字符串翻译对
# }
